# Generated by Django 3.0.8 on 2020-07-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktactoe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktactoe',
            name='linker',
            field=models.CharField(max_length=200),
        ),
    ]
