# Generated by Django 3.0.8 on 2020-07-06 15:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tiktactoe_app', '0002_auto_20200706_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktactoe',
            name='first_player',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
        migrations.AddField(
            model_name='tiktactoe',
            name='second_player',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
    ]
