# Generated by Django 3.0.8 on 2020-07-06 15:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tiktactoe_app', '0003_auto_20200706_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktactoe',
            name='linker',
            field=models.CharField(default=uuid.uuid4, max_length=200),
        ),
    ]
