# Generated by Django 3.0.8 on 2020-07-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktactoe_app', '0004_auto_20200706_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktactoe',
            name='first_player',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tiktactoe',
            name='second_player',
            field=models.CharField(max_length=100),
        ),
    ]
