# Generated by Django 3.0.8 on 2020-07-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktactoe_app', '0005_auto_20200706_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktactoe',
            name='first_player',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tiktactoe',
            name='second_player',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
