# Generated by Django 3.0.8 on 2020-07-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiktactoe_app', '0006_auto_20200706_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='move',
            new_name='sm_nos',
        ),
    ]
